const translations={
  en:{nav_story:'Story',nav_app:'App',nav_partners:'Partners',download:'Download',kicker:'CURATED IN KUWAIT',hero_1:'A new chapter',hero_2:'of modest elegance.',hero_body:'TERRAZ brings selected stores and considered pieces into one refined mobile destination.',discover:'Discover TERRAZ',s1_title:'Curated,\nnot crowded.',s1_body:'Selected stores, thoughtful pieces and less noise between you and what you came to find.',s2_title:'The piece\ncomes first.',s2_body:'A visual way to explore fashion, with product details kept close when you need them.',s3_title:'Move through\nit naturally.',s3_body:'Categories, discovery and product views connect as one focused mobile experience.',s4_title:'Designed\naround mobile.',s4_body:'TERRAZ is built to feel immediate in your hand — clear, visual and made for everyday browsing.',screen_label:'THE TERRAZ APP',inter_kicker:'NOT A CATALOGUE. A POINT OF VIEW.',inter_title:'A quieter way to\ndiscover what fits you.',inter_body:'TERRAZ brings fashion, stores and product discovery together without making the experience feel busy.',cap1:'The silhouette',cap2:'The essential',cap3:'The detail',final_kicker:'TERRAZ ON IPHONE',final_title:'Your next find\nstarts here.',final_body:'Explore TERRAZ on iPhone and move from discovery to product details in one place.',footer_line:'A new chapter of modest elegance.'},
  ar:{nav_story:'رحلة طراز',nav_app:'التطبيق',nav_partners:'الشركاء',download:'تحميل',kicker:'منتقى في الكويت',hero_1:'فصل جديد',hero_2:'من الأناقة المحتشمة.',hero_body:'يجمع طراز متاجر مختارة وقطعًا مدروسة في تجربة هاتف واحدة أكثر هدوءًا ووضوحًا.',discover:'اكتشف طراز',s1_title:'مختار بعناية،\nبلا ازدحام.',s1_body:'متاجر مختارة وقطع مدروسة، مع مساحة أوضح بينك وبين ما تبحث عنه.',s2_title:'القطعة\nأولاً.',s2_body:'تجربة بصرية لاكتشاف الأزياء، وتفاصيل المنتج قريبة عندما تحتاجها.',s3_title:'تنقّل\nبطبيعتك.',s3_body:'التصنيفات والاستكشاف وصفحات المنتجات مترابطة ضمن تجربة هاتف واحدة.',s4_title:'مصمم\nللهاتف.',s4_body:'طراز مصمم ليكون سريعًا وواضحًا وبصريًا في الاستخدام اليومي.',screen_label:'تطبيق طراز',inter_kicker:'مو مجرد كتالوج. عندنا وجهة نظر.',inter_title:'طريقة أهدأ\nلاكتشاف ما يناسبك.',inter_body:'يجمع طراز الأزياء والمتاجر والاستكشاف بدون ما يحول التجربة إلى زحمة.',cap1:'القصة',cap2:'الأساس',cap3:'التفاصيل',final_kicker:'طراز على الآيفون',final_title:'اكتشافك القادم\nيبدأ من هنا.',final_body:'اكتشف طراز على الآيفون وانتقل من الاستكشاف إلى تفاصيل المنتج في مكان واحد.',footer_line:'فصل جديد من الأناقة المحتشمة.'}
};
const screenSources=['assets/appstore/screen-1.jpg','assets/appstore/screen-2.jpg','assets/appstore/screen-4.jpg','assets/appstore/screen-3.jpg'];
const screenLabels=['EXPLORE','DETAILS','CATEGORIES','CART'];
let lang='en',scene=0,raf=0;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const header=$('.topbar'),story=$('.scroll-world'),device=$('.world-device'),screen=$('[data-screen]'),sceneLabel=$('[data-scene-label]');
function applyLanguage(next){lang=next;document.documentElement.lang=next;document.documentElement.dir=next==='ar'?'rtl':'ltr';document.body.dir=document.documentElement.dir;$$('[data-i18n]').forEach(el=>{const value=translations[next][el.dataset.i18n];if(value!==undefined)el.innerHTML=value.replace(/\n/g,'<br>')});$('[data-lang]').textContent=next==='en'?'عربي':'EN'}
function setScene(next){if(next===scene)return;scene=next;document.body.dataset.scene=String(next);$$('.world-bg figure').forEach((el,i)=>el.classList.toggle('is-on',i===next));$$('.scene-copy').forEach((el,i)=>el.classList.toggle('is-on',i===next));device?.classList.add('is-switching');setTimeout(()=>{if(screen)screen.src=screenSources[next];if(sceneLabel)sceneLabel.textContent=screenLabels[next];device?.classList.remove('is-switching')},150);const counter=$('.world-counter span');if(counter)counter.textContent=String(next+1).padStart(2,'0')}
function updateStory(){raf=0;header?.classList.toggle('is-scrolled',scrollY>24);if(!story)return;const rect=story.getBoundingClientRect(),range=story.offsetHeight-innerHeight;const p=Math.max(0,Math.min(1,-rect.top/Math.max(1,range)));story.style.setProperty('--story-progress',p.toFixed(4));setScene(Math.min(3,Math.floor(p*4-.0001<0?0:p*4)));if(device&&innerWidth>900){const drift=(p-.5)*18;device.style.transform=`translateY(calc(-48% + ${drift}px)) rotate(${(p-.5)*2}deg)`}}
function onScroll(){if(!raf)raf=requestAnimationFrame(updateStory)}
$('[data-lang]')?.addEventListener('click',()=>applyLanguage(lang==='en'?'ar':'en'));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');revealObserver.unobserve(e.target)}}),{threshold:.13});$$('.reveal').forEach(el=>revealObserver.observe(el));
if(device&&matchMedia('(pointer:fine)').matches){device.addEventListener('pointermove',e=>{const r=device.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;device.style.setProperty('--mx',x);device.style.setProperty('--my',y);if(innerWidth>900)device.style.transform=`translateY(-48%) perspective(900px) rotateY(${x*5}deg) rotateX(${-y*4}deg)`});device.addEventListener('pointerleave',()=>updateStory())}
window.addEventListener('scroll',onScroll,{passive:true});window.addEventListener('resize',onScroll,{passive:true});
applyLanguage('en');setScene(0);updateStory();const year=$('#year');if(year)year.textContent=String(new Date().getFullYear());
