const copy={
  en:{nav_about:'About',nav_inside:'Inside the app',nav_partners:'Partners',download:'Download',hero_kicker:'TERRAZ · KUWAIT',hero_title:'Shopping,<br><strong>curated.</strong>',hero_body:'Discover stores, new arrivals and products in one simple app.',hero_link:'See TERRAZ',tag_stores:'Stores',tag_explore:'Explore',about_label:'ABOUT',about_title:'One place.<br>Less friction.',about_body:'TERRAZ brings stores and products together in a cleaner shopping experience built around discovery.',about_link:'See the app',f1_title:'Discover stores',f1_body:'Browse selected stores from one place.',f2_title:'Explore products',f2_body:'Move through products visually and quickly.',f3_title:'Shop simply',f3_body:'From discovery to cart without the noise.',inside_kicker:'INSIDE TERRAZ',inside_title:'The app,<br>up close.',inside_body:'Real screens from TERRAZ. Swipe on mobile or move through them below.',g1:'Explore',g2:'Product details',g3:'Categories',g4:'Cart',partners_kicker:'FOR STORES',partners_title:'Sell on TERRAZ.',partners_body:'A dedicated space for stores that want to reach TERRAZ customers.',partners_link:'Partner login',final_kicker:'TERRAZ FOR IPHONE',final_title:'Open the app.<br>Start exploring.',final_body:'Download TERRAZ from the App Store and explore everything in one place.',footer_text:'Stores. Products. One app.'},
  ar:{nav_about:'عن طراز',nav_inside:'داخل التطبيق',nav_partners:'الشركاء',download:'تحميل',hero_kicker:'طراز · الكويت',hero_title:'كل اللي تبيه،<br><strong>بمكان واحد.</strong>',hero_body:'اكتشف المتاجر والجديد والمنتجات في تطبيق واحد بسيط.',hero_link:'اكتشف طراز',tag_stores:'المتاجر',tag_explore:'استكشف',about_label:'عن طراز',about_title:'مكان واحد.<br>تجربة أبسط.',about_body:'طراز يجمع لك المتاجر والمنتجات في تجربة مرتبة وواضحة تركّز على الاكتشاف.',about_link:'شوف التطبيق',f1_title:'اكتشف المتاجر',f1_body:'تصفّح متاجر مختارة من مكان واحد.',f2_title:'استكشف المنتجات',f2_body:'شوف المنتجات بسرعة وبشكل بصري.',f3_title:'تسوّق بسهولة',f3_body:'من الاكتشاف إلى السلة بخطوات واضحة.',inside_kicker:'داخل طراز',inside_title:'التطبيق،<br>عن قرب.',inside_body:'شاشات حقيقية من تطبيق طراز. اسحب على الموبايل وشوف التجربة.',g1:'استكشف',g2:'تفاصيل المنتج',g3:'التصنيفات',g4:'السلة',partners_kicker:'للمتاجر',partners_title:'بع على طراز.',partners_body:'مساحة مخصصة للمتاجر للوصول إلى عملاء طراز.',partners_link:'دخول الشركاء',final_kicker:'طراز على الآيفون',final_title:'افتح التطبيق.<br>وابدأ الاستكشاف.',final_body:'حمّل طراز من App Store واكتشف كل شيء في مكان واحد.',footer_text:'متاجر. منتجات. تطبيق واحد.'}
};
let lang='en';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function applyLanguage(next){lang=next;document.documentElement.lang=next;document.documentElement.dir=next==='ar'?'rtl':'ltr';document.body.dir=document.documentElement.dir;$$('[data-i18n]').forEach(el=>{const v=copy[next][el.dataset.i18n];if(v!==undefined)el.innerHTML=v});const btn=$('[data-lang]');if(btn)btn.textContent=next==='en'?'عربي':'EN'}
$('[data-lang]')?.addEventListener('click',()=>applyLanguage(lang==='en'?'ar':'en'));
const header=$('[data-header]');
const onScroll=()=>header?.classList.toggle('is-scrolled',window.scrollY>24);
window.addEventListener('scroll',onScroll,{passive:true});onScroll();
const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}})},{threshold:.14});
$$('.reveal').forEach(el=>observer.observe(el));
const tilt=$('[data-tilt]'),zone=$('[data-tilt-zone]');
if(tilt&&zone&&matchMedia('(pointer:fine)').matches){zone.addEventListener('pointermove',e=>{const r=zone.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;tilt.style.transform=`translate(18%,-1%) perspective(1000px) rotateY(${x*7}deg) rotateX(${-y*5}deg) rotateZ(4deg)`});zone.addEventListener('pointerleave',()=>tilt.style.transform='translate(18%,-1%) rotate(4deg)')}
applyLanguage('en');
const year=$('#year');if(year)year.textContent=String(new Date().getFullYear());
